---
include:
  - board: nice_nano
    shield: eyelash_sofle_central_dongle 
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: CYN_Sofle_central_dongle
  - board: nice_nano
    shield: eyelash_sofle_peripheral_left
    artifact-name: CYN_Sofle_left_hand
  - board: nice_nano
    shield: eyelash_sofle_peripheral_right
    artifact-name: CYN_Sofle_right_hand_with_ps2trackpoint
  - board: nice_nano
    shield: settings_reset






